/*
  What each function and tag on /journey does, shown when its chip is clicked.
  Ported from the Machine Map artifact, 14 September 2026.
*/
export type Owner = { c: 'self' | 'ops' | 'sean'; t: string };

export const SELF: Owner = { c: 'self', t: 'Runs itself, nobody touches it' };
export const OPS: Owner = { c: 'ops', t: 'Ops watches this' };
export const SEAN: Owner = { c: 'sean', t: 'Sean only' };

export type Part = {
  k?: string;
  o: Owner;
  fires: string;
  does: string;
  does2?: string;
  where: string[];
  broke: string;
  todo: string;
  infer?: string;
};

export const PARTS: Record<string, Part> = {
  "builder-application":{o:SELF,fires:"Someone submits the form at /builder or /apply.",does:"Fans out four ways at once: writes a page into Notion, posts the Slack card, adds them to ConvertKit, and creates the GoHighLevel contact by upsert so reapplying updates one record instead of making two. Returns the contact id that rides on their payment link.",where:["Slack","GoHighLevel contact","Notion"],does2:"Phone numbers are normalised to international format first, because GoHighLevel accepts a malformed number and then silently fails to text it.",broke:"If the Operator database variable is missing, Slack and GoHighLevel still fire and nothing reaches Notion. It logs loudly and carries on, so the applicant never sees a failure. Known open issue: the notification email arrives with blank fields.",todo:"Read the Slack card. That is the whole job at this stage."},
  "application-started":{o:SELF,fires:"Reads as firing when someone begins the form rather than finishing it.",does:"Writes the application-started tag so a half finished application is visible rather than invisible.",where:["GoHighLevel"],broke:"",todo:"Nothing. It exists so an abandoned form is not lost.",infer:"Purpose inferred from the tag it writes. Worth confirming against the GoHighLevel workflow."},
  "decide":{o:SEAN,fires:"Sean clicks one of the three buttons on the Slack card.",does:"Flips the tag in GoHighLevel, which is what triggers the next email. Invite sends the you're in email with their lock in link. Decline sends the decline. Send to concierge routes them to the operator intensive branch.",where:["Slack","GoHighLevel"],broke:"If the tag does not flip, no email sends and the applicant hears nothing. Check the contact in GoHighLevel and add the tag by hand.",todo:"This is the gate and it is deliberately manual. Once a day, every application. Nothing downstream moves until it is clicked."},
  "create-checkout-session":{o:SELF,fires:"Pay is clicked on the payment page.",does:"Creates the Stripe Checkout Session and passes the contact id as the client reference, so the payment matches the person rather than their email address.",where:["Stripe"],does2:"This matters because a personal address applies and a company card pays. Matching on email would split them into two people.",broke:"",todo:"Nothing."},
  "lock-in-paid":{o:SELF,fires:"Stripe sends them back to the success page after paying.",does:"Tags brand-day-paid in GoHighLevel.",where:["Stripe","GoHighLevel"],does2:"The success redirect is treated as the reliable paid signal, which is why the Brand Day needs no Stripe webhook at all.",broke:"If the tab closes before the redirect completes, the tag may not land, so no follow up email sends. Check Stripe for the payment, then add the tag by hand in GoHighLevel.",todo:"Worth a spot check: does every Stripe payment have a matching tagged contact."},
  "calendly-booked":{o:SELF,fires:"A Brand Day slot is picked.",does:"Tags brand-day-confirmed. Also writes booked-no-payment where a booking exists with no payment behind it.",where:["GoHighLevel","Calendar"],broke:"self-heal recreates the booking webhook if it disappears, so a silent failure here should repair itself within the hour.",todo:"Nothing routine. If booked-no-payment appears, that person booked without paying and needs a look."},
  "day-book-chase":{o:OPS,fires:"Every hour, all day.",does:"Finds anyone who paid for a Brand Day and never picked a date, and tags paid-no-date.",where:["GoHighLevel"],broke:"",todo:"This is Leak 01. The chase currently waits 48 hours. Anyone sitting here for more than a day should get a phone call, not another email. The planned fix is an immediate email on payment carrying the secure your day link."},
  "prep-call-chase":{o:OPS,fires:"8am daily.",does:"Finds anyone who booked the Brand Day but never booked the 20 minute prep call, and chases them. Sends a first chase, then a final one, then stops and says so in Slack.",where:["Slack","GoHighLevel"],broke:"",todo:"When the final chase fires and nothing happens, ring them. The prep call is the qualification gate, so a Brand Day without one is a day that should not go ahead."},
  "brand-day-followup":{o:SEAN,fires:"7am the morning after every Brand Day.",does:"Asks Sean one question in Slack: invite this client into the 90 days, yes or no. The answer writes the invite tag, which emails their /install link.",where:["Slack"],broke:"",todo:"One click, the morning after. If it is not clicked, the client hears nothing about the 90 days at all."},
  "sign-install":{o:SELF,fires:"The agreement is signed on the agreement page.",does:"Writes install-signed and step-1-signed.",where:["GoHighLevel"],does2:"install-signed is what gates the slot picker, so nobody can book calls without an agreement in place.",broke:"If the booking page refuses entry, the signing tag did not land. Check the contact before assuming the picker is broken.",todo:"Nothing."},
  "install-checkout":{o:SELF,fires:"Payment on the agreement page.",does:"Takes $5,000, payment one of two.",where:["Stripe"],broke:"",todo:"Nothing."},
  "verify-payment":{o:OPS,fires:"Straight after the install payment clears.",does:"Writes step-2-paid, raises the second $5,000 as a Stripe invoice set to take the saved card later, and sends the booking email.",where:["Stripe","GoHighLevel"],broke:"This is the one with history. Until 26 August the second $5,000 had never been invoiced for anybody, ever. Two independent faults: the instalment call was made with three arguments where it takes four, which made the idempotency keys global across all customers, and the invoice passed a due date alongside automatic charging, which Stripe refuses outright. Both fixed. It now guards on the data rather than on keys, because Stripe caches failed responses too and a failed key stays poisoned.",todo:"After every install payment, open Stripe and confirm a draft invoice exists for the second instalment. It is a ten second check and it is the one that was silently wrong for months."},
  "install-slot":{o:OPS,fires:"The slot picker is submitted.",does:"Creates ten Google Calendar events in one go and invites the operator to the weeklies. Seven weekly calls on weeks 1, 2, 3, 4, 5, 7 and 10, plus three board calls.",where:["Google Calendar","GoHighLevel"],does2:"Sends one confirmation email rather than ten separate invitations, which was the original behaviour and was hated. Availability is never stored: an hour is only offered if it is free on every date it would be used, read live from the calendar.",broke:"First call is always at least two weeks after signing, so if a client wants sooner it has to be moved by hand.",todo:"Check the operator's name and email came through correctly. The operator is invited to seven calls, so a typo there costs the whole 90 days."},
  "stripe-events":{o:SELF,fires:"Stripe calls the webhook.",does:"The only remaining Stripe webhook, kept for the install instalments.",where:["Stripe"],broke:"",todo:"Nothing."},
  "slot-chase":{o:OPS,fires:"9am daily.",does:"Finds anyone who signed, paid, then closed the tab without booking a single call.",where:["Slack","GoHighLevel"],broke:"",todo:"Someone in this state has paid $5,000 and has no calls in the diary. Ring them the same day."},
  "prep-nudge":{o:OPS,fires:"9am daily, targeting anyone with a call 48 hours away.",does:"Reads the content review database in Notion, and chases the client if their form has not come in.",where:["Notion","Slack"],does2:"The only job that reads Notion at all.",broke:"",todo:"If the form is still missing 24 hours out, chase it personally. A call without the form is a call spent finding out where the client is rather than moving forward."},
  "zoom-recording":{o:OPS,fires:"When Zoom finishes processing a call recording.",does:"Writes a debrief page into Notion, titled with the operator's name and the week number, or marked as a board call. Posts to Slack when it lands.",where:["Notion","Slack","Zoom"],broke:"If the parent page variable is not set, it writes the debrief, cannot file it, and warns in Slack that it has nowhere to go.",todo:"The debrief is raw material, not the recap. Read it, then post the recap and action list into the client's portal within 24 hours of the call."},
  "board-extend":{o:SELF,fires:"9am daily.",does:"Keeps creating the monthly board call so it runs through the full twelve months rather than stopping at day 90.",where:["Google Calendar"],does2:"Board slots are staggered across the first to fourth Friday over six hours, giving 24 slots. Slots do not recycle: a slot is held until that client leaves.",broke:"",todo:"Nothing routine. Board slots are the real capacity ceiling on ongoing clients, so watch how many are left."},
  "instalment-checkpoint":{o:OPS,fires:"9am daily.",does:"Gives three days notice in Slack before the second $5,000 is taken from a client's card.",where:["Slack","Stripe"],broke:"",todo:"This is the window. If a client is leaving, wobbling or in dispute, this is when to stop the charge. Once it goes, you are asking for a refund instead of preventing a charge."},
  "install-part-ways":{o:SEAN,fires:"Only when it is deliberately run.",does:"Voids the second instalment for a client leaving at day 30.",where:["Stripe"],does2:"Committed but not commanded. It does not fire on its own and nothing calls it automatically.",broke:"",todo:"Sean decides, then it gets run. Pair it with the instalment checkpoint: if someone is leaving, void it before the notice period ends."},
  "charge-install":{o:SEAN,fires:"Manual only.",does:"A fallback way to charge the install.",where:["Stripe"],does2:"Not the mechanism. The second instalment is raised as an invoice at the first payment, so this is only for when something has already gone wrong.",broke:"",todo:"Do not reach for this as a normal step. If you need it, something upstream failed and that is worth finding."},
  "client-upcoming":{o:SELF,fires:"When the client hub is opened.",does:"Tells the client what is coming up next.",where:["Client hub"],broke:"",todo:"Nothing."},
  "days-remaining":{o:SELF,fires:"When the client hub is opened.",does:"Counts down the days left in their install.",where:["Client hub"],broke:"",todo:"Nothing."},
  "track-hub":{o:SELF,fires:"When a client opens their hub.",does:"Tags hub-opened, so you can see who is actually looking at their portal.",where:["GoHighLevel"],broke:"",todo:"A client who never opens their hub is a client drifting. Worth a look before it becomes a problem."},
  "health-check":{o:SELF,fires:"Every hour.",does:"Checks the machine is alive and tags healthcheck-failed when it is not, so a failure cannot pass quietly.",where:["Slack","GoHighLevel"],broke:"Five draft workflows in GoHighLevel currently get called critical failures every hour. Deleting them is a one click job that stops the noise.",todo:"If the hourly check goes quiet or starts shouting, that comes first. Everything else depends on it."},
  "self-heal":{o:SELF,fires:"Every hour at 17 minutes past.",does:"Repairs rather than reports. Recreates the booking webhook if it disappears.",where:["Calendar"],broke:"",todo:"Nothing. This is the one that fixes things while you sleep."},
  "canary":{o:SELF,fires:"6am daily.",does:"Sends a real application all the way through and proves an email still comes out the other end. The full end to end test.",where:["Slack"],broke:"",todo:"If the canary complains, stop and look before doing anything else. It means a real applicant would also get nothing."},
  "capacity":{o:OPS,fires:"8am on Sundays.",does:"Reads Wednesday capacity live from the calendar. Six hours, each held for eleven weeks, is a hard ceiling on how many new clients can start.",where:["Google Calendar"],does2:"Wednesdays recycle every eleven weeks, which works out to roughly 2.4 new clients a month.",broke:"",todo:"Read this before promising anyone a start date. It is the honest answer to how many we can take."},

  "tag:applied":{k:"Tag",o:SELF,fires:"Written by builder-application the moment someone submits.",does:"The tag every downstream workflow hangs off. It triggers the application received email.",where:["GoHighLevel"],broke:"",todo:"If someone applied and heard nothing, check this tag exists on their contact first."},
  "tag:invited":{k:"Tag",o:SEAN,fires:"Written by decide when Sean clicks Invite.",does:"Replaces applied. Triggers the you're in email carrying their unique lock in link.",where:["GoHighLevel"],broke:"",todo:"This is the tag that turns an application into a sale. Nothing moves without it."},
  "tag:brand-day-paid":{k:"Tag",o:SELF,fires:"Written by lock-in-paid on the Stripe success redirect.",does:"Marks the $5,000 as collected.",where:["GoHighLevel","Stripe"],broke:"",todo:"Cross check against Stripe. A payment with no tag means the redirect did not complete."},
  "tag:paid-no-date":{k:"Tag",o:OPS,fires:"Written by day-book-chase, hourly.",does:"Marks someone who paid and never picked a Brand Day date.",where:["GoHighLevel"],broke:"",todo:"This is Leak 01 made visible. Anyone carrying this tag for more than a day gets a phone call."},
  "tag:install-signed":{k:"Tag",o:SELF,fires:"Written by sign-install when the agreement is signed.",does:"Gates the slot picker. Without it, /slot will not let them book.",where:["GoHighLevel"],broke:"",todo:"If a client says the booking page will not let them in, check this tag before anything else."},
  "tag:step-2-paid":{k:"Tag",o:OPS,fires:"Written by verify-payment once the install payment clears.",does:"Marks the first $5,000 of the install as collected and the second instalment as raised.",where:["GoHighLevel","Stripe"],broke:"",todo:"When this lands, open Stripe and confirm the draft invoice for the second instalment actually exists."},
  "tag:install-invited":{k:"Tag",o:SEAN,fires:"Written by decide off the morning after prompt.",does:"Triggers the email carrying their /install link with the agreement and checkout.",where:["GoHighLevel"],broke:"",todo:"Nothing beyond the click."}
  };
